source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Segment-Flurry_Example', :exclusive => true do
  pod "Segment-Flurry", :path => "../"
end

target 'Segment-Flurry_Tests', :exclusive => true do
  pod "Segment-Flurry", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
